### PR TITLE
Deploy OMERO.server 5.6.9 on pilot IDR instance

### PR DESCRIPTION
**Pull request by sbesson**
Not intended for production  usage yet (this will require a wider discussion and planning aroudn the upgrade of the OMERO.server as well as Bio-Formats)

### CODE REVIEW

**Comment by sbesson** [comment]
This should now be deployed onto `pilot-idr0125` in addition to `pilot-idr0138` /cc @will-moore

**Comment by sbesson** [comment]
The last commit has been deployed on `pilot-idr0125` and `pilot-idr0138` (as per the discussion in https://github.com/IDR/deployment/issues/389#issuecomment-1420582130). /cc @francesw @pwalczysko @dominikl @will-moore @khaledk2 @jburel 

Looking into recreating `pilot-idr0000` next

**Comment by sbesson** [comment]
This is now deployed on `pilot-idr-testing` as well /cc @dominikl

**Comment by dominikl** [comment]
Thanks @sbesson . I wonder, is there actually a reliable way to check it, e.g. `omero admin diagnostics` says: `Jar:        lib/server/omero-server.jar    jar	5.6.5` but shouldn't it be 5.6.6?

**Comment by sbesson** [comment]
From OMERO.py 5.13 moving forward, `omero admin diagnostics` should display the OMERO.server version. Can you try upgrading `omero-py` if it's too old and see if that works?

**Comment by dominikl** [comment]
👍 
The latest omero-py has an entry for omero server component:
`Component:  OMERO.server                   5.6.6-ice36`

The omero-server-jar apparently still is 5.6.5, but maybe that's fine:
`Jar:        lib/server/omero-server.jar    jar	5.6.5`

**Comment by pwalczysko** [comment]
> @pwalczysko @dominikl @will-moore @dgault which pilots should this be deployed to?

Definitely ``pilot-idrtesting`` please.

**Comment by sbesson** [comment]
> Definitely pilot-idrtesting please.

Upgraded, if you want to give it a try

**Comment by sbesson** [comment]
> Definitely pilot-idrtesting please.

Upgraded, if you want to give it a try

**Comment by pwalczysko** [comment]
> Thank you, I have idr0011 re-import in progress now.

this was a success, I would say that @dgault 's fix is working on idr0011, thanks

**Comment by sbesson** [comment]
Now deployed on `pilot-idr0125` - see https://github.com/IDR/idr-metadata/issues/652#issuecomment-1499965007 for the rationale /cc @will-moore

**Comment by will-moore** [comment]
@sbesson Just discussed with @dgault the possibility of including https://github.com/ome/ZarrReader/pull/41, which hopefully will allow us to import NGFF without chunks?

**Comment by sbesson** [comment]
The Ansible infrastructure downloads the JAR from a public location like the OME Artifactory. This is not straightforward to adapt as this work is currently at the Pull Request level.

If you are interested in testing the artifact, it should be more direct and more efficient to deploy it manually on the pilot of your choice. Simply replace the JARs under `lib/server` and `lib/client` in the standard OMERO.server location on the pilot server and restart the `omero-server` service.

**Comment by sbesson** [comment]
The last state of this PR was deployed on `test120`

**Comment by sbesson** [comment]
As discussed earlier today, merging this for the initial deployment of `prod120`. A follow-up PR will be required to bump `ZarrReader`.

**Pull request merged**
