### PR TITLE
Use 0.6.5 version of IDR Bio-Formats components

### PR DESCRIPTION
**Pull request by sbesson**
Deploys the the bug fix for the file handles from https://github.com/IDR/bioformats/pull/23

### CODE REVIEW

**Comment by sbesson** [comment]
Proposing to deploy this to `test90` for validation, in coordination with @manics who is also testing things on this deployment.

**Comment by manics** [comment]
Deployed to test90 (See https://github.com/IDR/deployment/pull/290)

**Review by manics — APPROVED** [review]
Tested following the mentioned PR, LGTM

**Comment by sbesson** [comment]
Deployed on `prod90`

**Pull request merged**
