### PR TITLE
Cache /gallery-api/

### PR DESCRIPTION
**Pull request by manics**
This might improve performance slightly

Not deployed, since it makes testing changes on test64 harder

### CODE REVIEW

**Comment by manics** [comment]
Deployed on test64 earlier today, and prod67 just now https://openmicroscopy.slack.com/archives/C0K5WAD8A/p1560268244220100

**Comment by joshmoore** [comment]
The changes seem fine and certainly the performance was _much_ faster on all subsequent calls. :+1: After release, we probably should (periodically?) have a system that _isn't_ using caching so we can figure out how to optimize the calls themselves. cc: @will-moore

**Comment by manics** [comment]
Hopefully web-dev-merge can be that system!

**Comment by joshmoore** [comment]
:+1:

**Pull request merged**
