### PR TITLE
Ansible playbook to dump postgres DB

### PR DESCRIPTION
**Pull request by manics**
Another decommissioning playbook to take a dump of the database. Requires Ansible 2.4

Used in https://trello.com/c/oEOqeKgR/31-re-snapshot-db

### CODE REVIEW

**Comment by manics** [comment]
Only the directory format supports parallel exports. I think that could be passed in `target_opts` but it means an extra step to zip up the directories. Since the dump is fairly small (2.9GB) I think it's easier to keep it as a single dump file.

If we're completely removing the dump script we'll need to ensure the database dump is still present for rsync access.

**Comment by sbesson** [comment]
The cards have not been updated for `prod60` which means I used the old script. Should I use this instead? What is the preferential way to allow the `rsync`?

**Comment by manics** [comment]
You'd probably need to run the dump task on omeroreadwrite. Can look at that in a future PR, but for now just use this for the backup dump?

**Comment by sbesson** [comment]
I have been trying to execute this playbook in the context of `prod52` decommissioning. A single 3.3GB `pgdump` was created under `/tmp` as expected however the playbook seemed to be hanging at the `Dump database` step. I will retry tomorrow but is there anything obvious I might be missing.

**Comment by manics** [comment]
Sounds about right, it takes a while with no apparent output.

**Comment by sbesson** [comment]
Ah yes, it completed. Just need to be a bit more patient.

**Pull request merged**
