### PR TITLE
Prometheus monitoring

### PR DESCRIPTION
**Pull request by manics**
Opening this to give a preview of what I've done so far.

### CODE REVIEW

**Comment by joshmoore** [comment]
Couple of quick comments from reviewing the transferred repos:
 * 0.1.0 for all three?
 * some still mention `idr-demo`
 * ...thought I had another one. Maybe after lunch...

**Comment by manics** [comment]
@joshmoore How would you feel about merging this as is (so not yet run by default).

**Comment by joshmoore** [comment]
Removed use of `idr-rsync`. Otherwise, uses public tags so :+1: for merging even before this is integrated into the standard deploy.

**Comment by manics** [comment]
--rebased-to #32

**Pull request merged**
