### PR TITLE
Redirect /curation-workflow

### PR DESCRIPTION
**Pull request by manics**
Final location is still to be decided

### CODE REVIEW

**Comment by manics** [comment]
Deployed to `test90`

**Review by joshmoore — APPROVED** [review]
Looks ok to me (even though the latest change hasn't been deployed: still redirects to github)

One thought: this does change the URL which means that users may book mark about/curation-workflow rather than /curation-workflow meaning we may need to redirect _both_.

**Comment by manics** [comment]
Deployed to all three deployments.

**Review by sbesson — APPROVED** [review]

**Comment by sbesson** [comment]
Merging despite this PR being still marked as draft. Can you push a tag to mark the fact this has been deployed to `prod89`?

**Comment by manics** [comment]
Sorry, didn't realise it still had a draft label. I'll push a tag `IDR-0.8.9-1`

**Pull request merged**
