### PR TITLE
Add grafana dashboards (IDR-0.4.2)

### PR DESCRIPTION
**Pull request by manics**
Adds Grafana to the management VM, and auto-configures some dashboards.

### CODE REVIEW

**Comment by joshmoore** [comment]
Nice! How close are we to being able to make these available without SSH-port forwarding? It would significantly increase their usability.

**Comment by manics** [comment]
Proxying would be easy, it's the security aspects I'm worried about. At the moment we know the only entry to everything apart from OMERO.web and jupyter is via a SSH tunnel.

**Comment by joshmoore** [comment]
And http auth over https?

**Comment by manics** [comment]
I've added an issue https://github.com/IDR/deployment/issues/49

**Comment by joshmoore** [comment]
Fair enough, but for me this falls under the "JRS usability" header (similar to the shared directory on jupyter) so we should target it as soon as possible.

(Less of a priority but a bigger impact would be having this/these as `openmicroscopy.*` roles, but one thing at a time :smile:)

**Pull request merged**
