### PR TITLE
Update requirements.yml to consume haproxy 3.1.0

### PR DESCRIPTION
**Pull request by sbesson**
As discussed earlier, the goal is to test the external changes proposed in https://github.com/openmicroscopy/ansible-role-haproxy/pull/12 against a complete deployment (`test51`)

### CODE REVIEW

**Comment by manics** [comment]
Are you proposing to merge this or is it a work-in-progress?

**Comment by sbesson** [comment]
I propose to deploy on `test51` for some testing, if this is succesful, I would cut a release of the role and update the PR to consume the new tag.

**Comment by manics** [comment]
OK, looks fine to deploy to me

**Comment by manics** [comment]
(sorry, hit the wrong button)

**Comment by sbesson** [comment]
Now deployed on `test51`

**Comment by joshmoore** [comment]
:+1:

**Pull request merged**
