### PR TITLE
More grafana dashboards. Enable anonymous access (IDR-0.4.4)

### PR DESCRIPTION
**Pull request by manics**
Anonymous access doesn't require a login, but it still allows read-access to all data. This must be reviewed if it is to be publicly proxied.

### CODE REVIEW

**Comment by joshmoore** [comment]
This _PR_ needs reviewing (before merging) or _Grafana_ must be reviewed before opening it up?

**Comment by manics** [comment]
I meant we need to review all information that's exposed _if_ we make direct anonymous access possible. At the moment only non-interactive images are public https://github.com/IDR/deployment/pull/66

**Comment by joshmoore** [comment]
I'm still not following. Can you outline what you'd like tested/reviewed here?

**Comment by manics** [comment]
Nothing really, the comment was a warning not to make this directly accessible to the public

**Pull request closed without merging**
