### PR TITLE
Bump OMERO.web and apps to versions compatible with Django 3.2

### PR DESCRIPTION
**Pull request by sbesson**
See https://www.openmicroscopy.org/2022/02/18/omeroweb-django-upgrade.html

### CODE REVIEW

**Comment by sbesson** [comment]
Run `idr-omero-web.yml` against `test104` (idr-testing). After some minimal testing  e.g. on the webclient, the viewer, the only broken behavior I  found so far are top-level URLs e.g. 

https://idr-testing.openmicroscopy.org/search/?query=Name:idr0001-graml-sysgro/screenA
http://idr-testing.openmicroscopy.org/search/?query=mapr_compound:aspirin

This seems to be limited to the gallery app. Other app URLs like  https://idr-testing.openmicroscopy.org/mapr/compound/?value=Aspirin work as expected.

@will-moore is this an issue of the overlap with the work happening in https://github.com/IDR/deployment/pull/364?

**Comment by pwalczysko** [comment]
> Run `idr-omero-web.yml` against `test104` (idr-testing). After some minimal testing e.g. on the webclient, the viewer, the only broken behavior I found so far are top-level URLs e.g.
> 
> https://idr-testing.openmicroscopy.org/search/?query=Name:idr0001-graml-sysgro/screenA http://idr-testing.openmicroscopy.org/search/?query=mapr_compound:aspirin
> 
> This seems to be limited to the gallery app. Other app URLs like https://idr-testing.openmicroscopy.org/mapr/compound/?value=Aspirin work as expected.
> 
> @will-moore is this an issue of the overlap with the work happening in #364?

Yes, confirming, the non-working urls are showing "Loading studies..." on the homepage.
Screenshot 2022-03-16 at 12 14 53

**Comment by will-moore** [comment]
Redeployed https://github.com/ome/omero-gallery/pull/96 on idr-testing and the issue above is fixed by that

**Comment by pwalczysko** [comment]
see https://github.com/ome/omero-gallery/pull/96#issuecomment-1069155624

**Comment by sbesson** [comment]
Released `omero-gallery 3.4.2` with the fix above and redeployed it on `test104`.

**Review by will-moore — APPROVED** [review]

**Comment by pwalczysko** [comment]
> Released omero-gallery 3.4.2 with the fix above and redeployed it on test104.

test104 ?

**Comment by sbesson** [comment]
> Maybe idr-testing is meant. If so, all seems good there.

Yes `test104` == `idr-testing` currently. I'll leave until tomorrow for a final round of comments and then we can merge this and focus on #364

**Pull request merged**
