### PR TITLE
Gallery is the idr root

### PR DESCRIPTION
**Pull request by manics**
~/ ➜ /gallery
/cell ➜ /gallery/cell
/tissue ➜ /gallery/tissue~

`/` is now the gallery app

### CODE REVIEW

**Comment by manics** [comment]
Deployed to test64. Travis will fail until gallery is updated with https://github.com/ome/omero-gallery/pull/33 since the molecule proxy test checks for the IDR title string.

**Comment by joshmoore** [comment]
:+1: slash endings are missing for the likes of https://X/cell/

Was hiding the `/gallery/` element from the URL doable?

**Comment by manics** [comment]
Added `/` handling.

Rewrites are not supported by the current Ansible role. In any case Django apps don't support rewriting, they need to know their full location. It might be possible to develop a custom set of rewrite rules but they'd be liable to break when the app is modified.

**Comment by joshmoore** [comment]
> but they'd be liable to break when the app is modified.

With the flip-side being the URLs are guaranteed to break if we drop `/gallery/` moving forward.

**Comment by manics** [comment]
Redirecting is easy, rewriting to hide a URL isn't.

**Comment by manics** [comment]
Deployed to test64

**Comment by manics** [comment]
I can't fix travis until https://github.com/IDR/deployment/pull/179 and https://github.com/will-moore/deployment/pull/1 are merged, since the molecule test  checks the response from `/`

**Pull request merged**
