### PR TITLE
Include public user/pass in omero-client.json

### PR DESCRIPTION
**Pull request by manics**
Closes https://github.com/IDR/deployment/issues/245

Deployed to `test84`

# Testing
```py
from idr import connection
conn = connection('test84.example.org', verbose=2)
for p in conn.listProjects():
    print(p.name)
```

### CODE REVIEW

**Comment by joshmoore** [comment]
`http://X/connection/omero-client.json` looks good to me. (We might just need to be ready to scale up ;) )

**Comment by manics** [comment]
I think we should slim down idr-py or extract the connection method if we want everyone to install it, at the moment it pulls in a lot of analysis/pydata/jupyter dependencies

**Comment by joshmoore** [comment]
:+1:

**Comment by manics** [comment]
Or move it upstream 😀
https://github.com/ome/design/issues/106

**Comment by manics** [comment]
Deployed to `prod84`

**Pull request merged**
