### PR TITLE
Increase number of omeroreadonly from 2 to 4 (IDR-0.4.6)

### PR DESCRIPTION
**Pull request by manics**
Self explanatory.

### CODE REVIEW

**Comment by sbesson** [comment]
While testing the redeployment of `test45`, realized that `scripts/os-idr-delete.sh` should be updated accordingly.

**Comment by manics** [comment]
Updated

**Comment by manics** [comment]
I guess this should be pushed to 0.4.6? Then we can also test reducing the resource allocations to the read-only instances.

**Comment by manics** [comment]
Rebased, and cut down the size of the omero-readonly servers to 32GB.

**Pull request merged**
