### PR TITLE
Restore 

### PR DESCRIPTION
**Pull request by aleksandra-tarkowska**
This Playbook allows to restore prod db from rsync

### CODE REVIEW

**Comment by manics** [comment]
can you:
- rebase this
- the added playbook isn't run routinely as part of our deployments, so how about putting it in a subdirectory?
- why do you need global variables `group_vars/all`?

**Comment by aleksandra-tarkowska** [comment]
> - the added playbook isn't run routinely as part of our deployments, so how about putting it in a subdirectory?

any particular name for subdir?

> - why do you need global variables group_vars/all?

vars are scoped to host how I would make rsync shared across db and omero hosts?

**Comment by manics** [comment]
> any particular name for subdir?

Something like maintenance, contrib, external, utils, .... depending on what other playbooks you're thinking of.

> how I would make rsync_host shared across db and omero hosts

I think I'd just duplicate it in the playbook since it's all self-contained.

**Comment by joshmoore** [comment]
Closing for the moment.

**Pull request closed without merging**
