### PR TITLE
Bump idr-gallery to 3.9.0

### PR DESCRIPTION
**Pull request by will-moore**
cc @jburel

### CODE REVIEW

**Comment by jburel** [comment]
This should be deployed when ready green so we can do some final check

**Comment by sbesson** [comment]
Understood. Deployed on `test114` and ready for a round of testing then.

**Comment by will-moore** [comment]
As we found on the last release, testing on idr-next isn't possible for the search engine as it's not available at that URL,
E.g. http://idr-next.openmicroscopy.org/searchengine/api/v1/resources/image/searchvalues/?value=idr is 500 Error

**Comment by sbesson** [comment]
> As we found on the last release, testing on idr-next isn't possible for the search engine as it's not available at that URL,
E.g. http://idr-next.openmicroscopy.org/searchengine/api/v1/resources/image/searchvalues/?value=idr is 500 Err

```
[sbesson@prod114-searchengine ~]$ df -h | grep data
/dev/vdb         75G   34M   75G   1% /data
```

It feels like the indexer should be run first no?

**Comment by pwalczysko** [comment]
@sbesson - sorry, cannot make a sense of the conversation above
1. Is this deployed now on idr-next ?
2. Is this deployed now on idr-testing ?
3. If any of those questions are answered by No, will that be deployed on idr-testing or idr-next automatically at 3 pm ?
4. Should we be running the indexer now and where ?

**Comment by sbesson** [comment]
> 1. Is this deployed now on idr-next ?

No, it has not been deployed on `prod114` yet

> 2. Is this deployed now on idr-testing ?

Yes as per https://github.com/IDR/deployment/pull/393#issuecomment-1411998732 

> 3. If any of those questions are answered by No, will that be deployed on idr-testing or idr-next automatically at 3 pm ?

Happy to deploy on `prod114` anytime. This has to be done manually

> 4. Should we be running the indexer now and where ?

Completely deferring to you guys as this depends on the state of the database

**Comment by pwalczysko** [comment]
lgtm on idr-testing

**Review by pwalczysko — APPROVED** [review]

**Review by jburel — APPROVED** [review]

**Comment by sbesson** [comment]
`prod114` has been updated with the new gallery version

**Comment by pwalczysko** [comment]
> `prod114` has been updated with the new gallery version

on idr-next:
I can see the ``prod 114`` as version and the GS logo
I cannot see the autocomplete on search, probably because of what @will-moore indicated ? https://github.com/IDR/deployment/pull/393#issuecomment-1412088625

Screenshot 2023-02-01 at 17 30 24

**Comment by sbesson** [comment]
@pwalczysko my understanding is that the database is getting indexed as we speak. I would confirm the state of the indexing process with @khaledk2 tomorrow morning before running the search UI tests on `prod114`

**Comment by khaledk2** [comment]
Yes, the indexer has started form about 2 hours.

**Pull request merged**
