### PR TITLE
Search engine documentation review

### PR DESCRIPTION
**Pull request by sbesson**
Review the searchengine documentation introduced in #359:

- rename the file to fix a typo
- add links to the repositories
- updates the ports for the engine and the client
- add links to the playbooks
- remove the unnecessary pg_hba.conf section as the configuration should be handled via the playbook (?)

### CODE REVIEW

**Review by khaledk2 — CHANGES_REQUESTED** [review]
The next line should be modified 
`http://127.0.0.1:5577/api/v1/resources/` 
The script_name `searchengineapi` is set by gunicon for the searchengine, so it should be a part of the URL, so it needs to be like that:
`http://127.0.0.1:5577/searchengineapi/api/v1/resources/`

**Comment by sbesson** [comment]
Thanks @khaledk2, looking at the `pilot-idr0000` deployment, I have

```
[sbesson@pilot-idr0000-omeroreadwrite ~]$ curl  http://127.0.0.1:5577/api/v1/resources/
Omero search engine (API V1)[sbesson@pilot-idr0000-omeroreadwrite ~]$ 
[sbesson@pilot-idr0000-omeroreadwrite ~]$ curl  http://127.0.0.1:5577/searchengineapi/api/v1/resources/
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<title>404 Not Found</title>
<h1>Not Found</h1>
<p>The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.</p>
[sbesson@pilot-idr0000-omeroreadwrite ~]$ 
```

Is there a special configuration required to get the new endpoint?

**Comment by khaledk2** [comment]
I think you have deployed it before the latest modifications which I have pushed. 
`https://github.com/IDR/deployment/pull/359#issuecomment-1112753968`

You may be re-run the deployment ansible-playbook again or just pull the latest docker image for the search engine and run the container. The latest can be done using the following commands:
`sudo docker pull openmicroscopy/omero-searchengine:latest`
`sudo docker stop searchengine`
`sudo docker run -d  --name searchengine  --rm  -v /data/searchengine/searchengine/:/etc/searchengine/ --network=searchengine-net  -p 5577:5577  openmicroscopy/omero-searchengine:latest run_app searchengineapi`

**Comment by sbesson** [comment]
Thanks, pulling the latest image and redeploying it fixes the endpoint and  [82b144c](https://github.com/IDR/deployment/pull/369/commits/82b144ca6b72c9e4d7413998d289650737535400)updates the documentation accordingly.

This highlights the issue associated with using mutable images for the deployment. I'll open a separate issue to discuss the container versioning/lifecycle.

**Comment by khaledk2** [comment]
It looks fine, thank you.

**Pull request merged**
