### PR TITLE
update mapr config to match 0.1.12

### PR DESCRIPTION
**Pull request by aleksandra-tarkowska**
cc @joshmoore @manics 

if boolean doesnt work we can wrap them in `""`

--depends-on https://github.com/ome/omero-mapr/pull/18

### CODE REVIEW

**Comment by manics** [comment]
Does this need to be updated too? https://github.com/IDR/deployment/blob/master/ansible/group_vars/omero-hosts.yml#L31

**Comment by joshmoore** [comment]
```
TASK [omero-web-apps : system pip | install webapp] ****************************
failed: [idr-omero-docker] (item=omero-mapr==0.1.11) => {"cmd": "/usr/bin/pip install omero-mapr==0.1.11", "failed": true, "item": "omero-mapr==0.1.11", "msg": "stdout: Collecting omero-mapr==0.1.11\n\n:stderr:   Could not find a version that satisfies the requirement omero-mapr==0.1.11 (from versions: 0.1.1, 0.1.2, 0.1.3, 0.1.4, 0.1.5, 0.1.6, 0.1.7, 0.1.8, 0.1.9, 0.1.10)\nNo matching distribution found for omero-mapr==0.1.11\nYou are using pip version 8.1.2, however version 9.0.1 is available.\nYou should consider upgrading via the 'pip install --upgrade pip' command.\n"}

```

**Comment by aleksandra-tarkowska** [comment]
did you release 1.11 ?

**Comment by joshmoore** [comment]
No, did you tell me to? :smile: (Now done)

**Comment by aleksandra-tarkowska** [comment]
when the time comes it will be green

**Comment by aleksandra-tarkowska** [comment]
keep in mind that this config covers https://github.com/ome/omero-mapr/pull/18 as well. So lets wait for everything

**Comment by aleksandra-tarkowska** [comment]
@manics @joshmoore could you please deploy new proxy config on test34 ?

**Comment by joshmoore** [comment]
Testing with `--diff -C` now.

**Comment by joshmoore** [comment]
Doh, `-C` leads to config items being skipped.

**Comment by aleksandra-tarkowska** [comment]
@eleanorwilliams @joshmoore config is not updated, see https://trello.com/c/NnhUb1Se/41-add-new-mapr-category-of-antibody-o-org-mapr-antibody

**Comment by joshmoore** [comment]
NB: Jason suggested let's leave it at just `Organisms` with a default search.

**Comment by joshmoore** [comment]
Re-opening to test `0.1.12` version of mapr.

**Comment by joshmoore** [comment]
Merging for using `master` against demo34. If there are any adjustments needed, let's do that in a follow-up.

**Pull request merged**
