### PR TITLE
Switch from idr-demo to idr (IDR-0.3.6)

### PR DESCRIPTION
**Pull request by manics**
This will not work until the following are renamed:
- [x] https://github.com/IDR/idr-demo.openmicroscopy.org.git
- [x] https://github.com/IDR/idr-notebooks/blob/master/library/idr_demo.py
  - https://github.com/IDR/idr-notebooks/pull/15

### CODE REVIEW

**Comment by joshmoore** [comment]
```
TASK [openmicroscopy.jekyll-build : jekyll | clone site source code repository]
fatal: [idr-proxy-docker]: FAILED! => {"changed": false, "cmd": "/usr/bin/git clone --origin origin https://github.com/IDR/idr.openmicroscopy.org.git /home/omero/about", "failed": true, "msg": "fatal: could not read Username for 'https://github.com': No such device or address", "rc": 128, "stderr": "fatal: could not read Username for 'https://github.com': No such device or address\n", "stdout": "Cloning into '/home/omero/about'...\n", "stdout_lines": ["Cloning into '/home/omero/about'..."]}
```

Restarting build.

**Comment by manics** [comment]
--depends-on https://github.com/openmicroscopy/ansible-role-nginx-proxy/pull/1

**Comment by manics** [comment]
- [ ] https://github.com/IDR/idr-notebooks/ needs a tag

**Comment by joshmoore** [comment]
IDR-0.3.6 pushed.

**Comment by joshmoore** [comment]
Merging as the current state of prod36 for tagging with IDR-0.3.6. If there are any minor modifications needed, we can either re-tag or include in IDR-0.3.7

**Pull request merged**
