### PR TITLE
Remove redirect for idr0078

### PR DESCRIPTION
**Pull request by sbesson**
In preparation of the final checks, removes the top-level redirect to the downloads page

### CODE REVIEW

**Comment by sbesson** [comment]
Deployed on `prod88`

**Comment by francesw** [comment]
I still see the redirect on idr-next (prod88).

**Comment by francesw** [comment]
I still see the redirect on idr-next (prod88).

**Comment by sbesson** [comment]
Sorry, I must have reverted the change as part of the work to fix redirects on #273. Redeployed to `prod88` now

**Pull request merged**
